# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- v2

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Maven@4
  inputs:
    mavenVersionOption: '3.9.9'
    mavenPomFile: 'lib/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: mkdir -p docs && cp target/atg-api-1.4.1-SNAPSHOT-javadoc.jar docs/ && cd docs && jar -xvf atg-api-1.4.1-SNAPSHOT-javadoc.jar
  workingDirectory: lib
  displayName: 'Extract javadoc'
- task: AzureCLI@2
  inputs:
    displayName: 'Copy javadocs'
    inlineScript: |
      az storage blob upload-batch \
        --account-name atgapi \
        --destination-path="v1" \
        --destination=\$web \
        --source docs

