# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- v2

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Maven@4
  inputs:
    mavenVersionOption: '3.9.9'
    mavenPomFile: 'lib/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
- script: ls target && jar --help && mkdir -p docs && jar --verbose --extract --file target/atg-api-1.4.1-SNAPSHOT-javadoc.jar -C docs
  workingDirectory: lib
  displayName: 'Extract javadoc'
- task: AzureFileCopy@4
  displayName: Deploy javadoc
  inputs:
    SourcePath: 'docs'
    Destination: AzureBlob
    storage: atgapi
    ContainerName: web
    BlobPrefix: v1
