name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      RELEASE_NAME: 0.0.1-SNAPSHOT #${{ github.event.release.tag_name }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: maven
    - name: Setup credentials
      run: |
        touch settings.xml
        echo "<settings><servers><server><id>central</id><username>${{ secrets.MAVEN_CENTRAL_USERNAME }}</username><password>${{ secrets.MAVEN_CENTRAL_PASSWORD }}</password></server></servers></settings>" > settings.xml
    - name: Push to Maven Central
      working-directory: ./lib
      run: |
        mvn versions:set -DnewVersion=${RELEASE_NAME} -DprocessAllModules -DgenerateBackupPoms=false
        mvn -P release clean deploy
